sa = r"F:\Code\Python\run_any_code\run;C:\Program Files\WindowsApps\Microsoft.PowerShell_7.2.6.0_x64__8wekyb3d8bbwe;C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.15.2525.0_x64__8wekyb3d8bbwe;C:\Program Files\ImageMagick-7.1.0-Q16-HDRI;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\Cloudflare\Cloudflare WARP\;C:\Program Files\GitHub CLI\;C:\Program Files\WindowsApps\Microsoft.PowerShell_7.2.6.0_x64__8wekyb3d8bbwe;C:\Program Files\ImageMagick-7.1.0-Q16-HDRI;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\Cloudflare\Cloudflare WARP\;C:\Program Files\GitHub CLI\;C:\Users\hossa\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\hossa\AppData\Local\Programs\Python\Python310\;C:\Users\hossa\AppData\Local\Programs\;C:\Users\hossa\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.10;D:\Aditional Tools\MinGW\bin;C:\Users\hossa\AppData\Local\Programs\Microsoft VS Code\bin;"

sb = "C:\\Program Files\\WindowsApps\\Microsoft.PowerShell_7.2.6.0_x64__8wekyb3d8bbwe;C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.15.2525.0_x64__8wekyb3d8bbwe;C:\\Program Files\\ImageMagick-7.1.0-Q16-HDRI;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\dotnet\\;C:\\Program Files\\Cloudflare\\Cloudflare WARP\\;C:\\Program Files\\GitHub CLI\\;C:\\ProgramData\\chocolatey\\bin;F:\\Code\\Python\\run_any_code\\run;C:\\Program Files\\WindowsApps\\Microsoft.PowerShell_7.2.6.0_x64__8wekyb3d8bbwe;C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.15.2525.0_x64__8wekyb3d8bbwe;C:\\Program Files\\ImageMagick-7.1.0-Q16-HDRI;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\dotnet\\;C:\\Program Files\\Cloudflare\\Cloudflare WARP\\;C:\\Program Files\\GitHub CLI\\;C:\\Program Files\\WindowsApps\\Microsoft.PowerShell_7.2.6.0_x64__8wekyb3d8bbwe;C:\\Program Files\\ImageMagick-7.1.0-Q16-HDRI;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\dotnet\\;C:\\Program Files\\Cloudflare\\Cloudflare WARP\\;C:\\Program Files\\GitHub CLI\\;C:\\Users\\hossa\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\;C:\\Users\\hossa\\AppData\\Local\\Programs\\Python\\Python310\\;C:\\Users\\hossa\\AppData\\Local\\Programs\\;C:\\Users\\hossa\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Python 3.10;D:\\Aditional Tools\\MinGW\\bin;C:\\Users\\hossa\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;"

a_path = sa.split(";")
b_path = sb.split(";")

common = [x for x in a_path if x in b_path]
print(common)
